{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "68f2241c_a640c047",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1512169
      },
      "writtenOn": "2022-11-30T08:14:38Z",
      "side": 1,
      "message": "Issues fixed, PTAL",
      "revId": "8e8aac246916cd4dcd62a54ebff709d80dcd18d8",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "a1a4b31a_423dfaf7",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1003232
      },
      "writtenOn": "2022-11-30T20:27:45Z",
      "side": 1,
      "message": "It is annoying that catapult isn\u0027t fully migrated to python3; I hope that is being actively worked on, because you\u0027re at least a year late.\n\nThat said, this fix lgtm.",
      "revId": "8e8aac246916cd4dcd62a54ebff709d80dcd18d8",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}