{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2c1ef394_408e909e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1181219
      },
      "writtenOn": "2021-05-11T21:01:27Z",
      "side": 1,
      "message": "More Python 3 fix. PTAL.",
      "revId": "93fe5694aa737728fe5c173a2a6819e2d0d6be64",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}