{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "17663fad_f33f7dd5",
        "filename": "systrace/systrace/tracing_agents/atrace_agent.py",
        "patchSetId": 4
      },
      "lineNbr": 354,
      "author": {
        "id": 1181219
      },
      "writtenOn": "2021-07-20T00:18:10Z",
      "side": 1,
      "message": "trace_data.startswith(b\u0027\\n\u0027) should work on both Python 2 and 3.",
      "range": {
        "startLine": 354,
        "startChar": 5,
        "endLine": 354,
        "endChar": 36
      },
      "revId": "98a4a0e2914cf378185eefbeaa3bd22fa2d6cd14",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}